[package]
name = "bjorn"
version = "0.0.0"
authors = ["Matthieu Gouel <matthieu.gouel@gmail.com>"]
description = "Foolish attempt to build an interpreter."

[dependencies]
clap = "~2.32.0"
unicode-segmentation = "~1.2.1"
regex = "~1.0.5"
lazy_static = "~1.1.0"
